depth:
  type: None
pose:
  learn_pose: True
dataloading:
  path: data/Blender
  scene: ['test-anything']
  load_colmap_poses: False
  customized_focal: False
training:
  out_dir:  out/Blender/test-anything
  auto_scheduler: True
  eval_pose_every: -1
extract_images:
  resolution: [384, 384]