depth:
  type: None
pose:
  learn_pose: True
dataloading:
  path: data/CVLab
  scene: ['SwissCube']
  load_colmap_poses: False
  customized_focal: True
training:
  out_dir:  out/CVLab/SwissCube
  auto_scheduler: True
  eval_pose_every: -1
extract_images:
  resolution: [540, 960]