depth:
  type: None
pose:
  learn_pose: True
dataloading:
  path: data/KITTI
  scene: ['straight']
  customized_focal: true
  customized_poses: false
  load_colmap_poses: true
  random_ref: 1
training:
  auto_scheduler: True
  out_dir: out/KITTI/straight
extract_images:
  resolution: [188, 621]
